In [4]:
print("Retail Intelligence Project")
print("Python environment is ready!")

Retail Intelligence Project
Python environment is ready!

In [5]:
import sys

print(sys.executable)

/Users/gowthamrajana/Desktop/retail-intelligence/.venv/bin/python

In [6]:
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Seaborn:", sns.__version__)

Pandas: 3.1.0
NumPy: 2.5.4
Matplotlib: 3.11.2
Seaborn: 0.13.2

In [7]:
sales = 1000

In [8]:
print(sales)

1000

# Retail Dataset — Initial Inspection

Source: UCI Machine Learning Repository
Dataset: Online Retail II

In [9]:
from pathlib import Path
import pandas as pd

data_path = Path("../data/raw/online_retail_II.xlsx")

print("File exists:", data_path.exists())

if data_path.exists():
    print("File size (MB):", round(data_path.stat().st_size / (1024 * 1024), 2))

File exists: True
File size (MB): 43.51

In [10]:
excel_file = pd.ExcelFile(data_path)
print("Available sheets:")
print(excel_file.sheet_names)

Available sheets:
['Year 2009-2010', 'Year 2010-2011']

In [11]:
for sheet in excel_file.sheet_names:
  print(f"\nsheet: {sheet}")
  sample = pd.read_excel(
    excel_file,
    sheet_name=sheet,
    nrows=5
  )
  display(sample)

sheet: Year 2009-2010

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom

sheet: Year 2010-2011

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [12]:
import pandas as pd
from pathlib import Path

data_path = Path("../data/raw/online_retail_II.xlsx")

df = pd.read_excel(
  data_path,
  sheet_name=0
)

print("Dataset loaded sucessfully")

Dataset loaded sucessfully